### ISSUE TITLE
Refs: Software Transactional Memory

### ISSUE THREAD

**Issue by fwbrasil** [getkyo/kyo#104]
initial impl https://github.com/getkyo/kyo/commit/ecc3cf6a31f98f750f78954f4dec51a31f42da1e

**Comment by ajaychandran** [comment]
Related work that might be worth considering:
- [Efficient Multi-word Compare and Swap](https://arxiv.org/abs/2008.02527)
- [kcas](https://github.com/ocaml-multicore/kcas)
- [choam](https://github.com/durban/choam)

**Comment by fwbrasil** [comment]
fixed by https://github.com/getkyo/kyo/pull/878
