### ISSUE TITLE
Cannot run certain effects without explicitly annotating expected return type

### ISSUE THREAD

**Issue by johnhungerford** [getkyo/kyo#139]
## Expected Behavior
You should be able to run an effect without explicitly annotating the return type

## Current Behavior
In some cases, there are compilation errors when a `run` method is called without explicitly annotating the expected result type

## Minimized example

*Note: the same problem arises when you do not include `Envs[String]` in `Example.effect`, but it is resolved when you get rid of `Options`*

```scala
import kyo.*
import kyo.consoles.*
import kyo.envs.*
import kyo.options.*
import kyo.aborts.*

final case class Dep(int: Int)

object Example:
   // Given the following effect:
   val effect = for {
      int1 <- Envs[Dep].get.map(_.int)
      int2 <- Options.get(Some(23))
      int3 <- Aborts[String].get(Right(50))
      _ <- Consoles.println((int1 + int2 + int3).toString)
   } yield ()

   // Compiles
   val withOptionsRun: Option[Unit] > (Consoles & Aborts[String] & Envs[Dep]) =
      Options.run(effect)
   val withEnvsRun: Unit > (Consoles & Aborts[String] & Options) =
      Envs[Dep].run(Dep(900))(effect)
   val withAbortsRun: Either[String, Unit] > (Consoles & Options & Envs[Dep]) =
      Aborts[String].run(effect)

   // Does not compile
   val withOptionsRunInferred = Options.run(effect)
   val withEnvsRunInferred = Envs[Dep].run(Dep(900))(effect)

   // Compiles (???)
   val withAbortsRunInferred = Aborts[String].run(effect)
  
```

Error message from `withOptionsRunInferred`:
```
Method doesn't accept nested Kyo computations. Detected: 'scala.Unit > kyo.envs.Envs[Dep] & kyo.consoles.Consoles & kyo.options.Options & kyo.aborts.Aborts[scala.Predef.String] > kyo.options.Options'.
Consider using 'flatten' to resolve. Possible pending effects mismatch: Expected 'kyo.options.Options', found 'kyo.envs.Envs[Dep] & kyo.consoles.Consoles & kyo.options.Options & kyo.aborts.Aborts[scala.Predef.String]'.
```

Error message from `withEnvsRunInferred`:
```
Method doesn't accept nested Kyo computations. Detected: 'scala.Unit > kyo.envs.Envs[Dep] & kyo.consoles.Consoles & kyo.options.Options & kyo.aborts.Aborts[scala.Predef.String] > kyo.envs.Envs[Dep]'.
Consider using 'flatten' to resolve. Possible pending effects mismatch: Expected 'kyo.envs.Envs[Dep]', found 'kyo.envs.Envs[Dep] & kyo.consoles.Consoles & kyo.options.Options & kyo.aborts.Aborts[scala.Predef.String]'.
```

## Context (Environment)
Scala 3.3.1
kyo 0.7.0

**Comment by fwbrasil** [comment]
Thanks for the report! It think it's some limitation or bug in the Scala's type inference. It seems there's something special about `Aborts`. If I remove it, the code works without type annotations but fails to compile if I put it back. I also included several other effects and tried to move the `Aborts` call to different positions of the for-comprehension but the code only fails to compile when `Aborts` is used. Other effects seem unaffected. 

Minimized repro:

```scala
import kyo.*
import kyo.consoles.*
import kyo.ios.*
import kyo.envs.*
import kyo.options.*
import kyo.aborts.*
import kyo.tries.*
import kyo.lists.*
import kyo.concurrent.fibers.*

object Example {
  val effect = for {
    _ <- Envs[Int].get
    _ <- Options.get(Some(23))
    _ <- IOs(10)
    _ <- Fibers.parallel(List(1, 2)).map(_.sum)
    _ <- Tries(42)
    _ <- Lists.foreach(List(33, 44))
    _ <- Aborts[String].get(Right(50))
  } yield ()

  // Does not compile
  val withOptionsRunInferred = Options.run(effect)
  val withEnvsRunInferred    = Envs[Int].run(900)(effect)

  // Compiles (???)
  val withAbortsRunInferred = Aborts[String].run(effect)
}
```

The error message comes from the [flat check macro](https://github.com/getkyo/kyo/blob/main/kyo-core/shared/src/main/scala-3/kyo/internal/FlatImplicits.scala) but it's actually a symptom. For some reason, Scala isn't able to infer that the effect is part of the pending set once `Aborts` is introduced. When this kind of mismatch happen, the compiler ends up widening to `T > Effects > Any`, which the macro detects.

Another interesting piece of information: [Aborts](https://github.com/getkyo/kyo/blob/main/kyo-core/shared/src/main/scala/kyo/aborts.scala) and [Envs](https://github.com/getkyo/kyo/blob/main/kyo-core/shared/src/main/scala/kyo/envs.scala) are remarkably similar in structure but the issue only happens with `Aborts`.

**Comment by johnhungerford** [comment]
Yeah I was surprised to see the issue arise with aborts and not with envs (I originally assumed it had to do with the type parameter, which I know can complicate type inference). This will complicate usage. Do you think it's worth adding a message to the flatcheck error warning users about the issue?

**Comment by fwbrasil** [comment]
I couldn't reproduce anymore. I'm not sure what fixed it so please feel free to reopen this issue if you encounter it again.

```scala
package kyo

import kyo.*

final case class Dep(int: Int)

object Example:
    // Given the following effect:
    val effect =
        for
            int1 <- Envs[Dep].get.map(_.int)
            int2 <- Options.get(Some(23))
            int3 <- Aborts[String].get(Right(50))
            _    <- Consoles.println((int1 + int2 + int3).toString)
        yield ()

    // Compiles
    val withOptionsRun: Option[Unit] < (IOs & Aborts[String] & Envs[Dep]) =
        Options.run(effect)
    val withEnvsRun: Unit < (IOs & Aborts[String] & Options) =
        Envs[Dep].run(Dep(900))(effect)
    val withAbortsRun: Either[String, Unit] < (IOs & Options & Envs[Dep]) =
        Aborts[String].run(effect)

    // Does not compile
    val withOptionsRunInferred = Options.run(effect)
    val withEnvsRunInferred    = Envs[Dep].run(Dep(900))(effect)

    // Compiles (???)
    val withAbortsRunInferred = Aborts[String].run(effect)
end Example
```
