### ISSUE TITLE
Logs review

### ISSUE THREAD

**Issue by fwbrasil** [getkyo/kyo#148]
I recently changed the [logging support](https://github.com/getkyo/kyo/blob/main/kyo-core/shared/src/main/scala/kyo/logs.scala) to avoid having to create logger instances. Instead, the sourcecode library is used to identify the source of the log via the file name and line. This simplification should be helpful for newcomers but there are still a few topics to explore:

1. I'd be nice to have a way to switch the underlying logger like `Consoles` does so users can dynamically change log levels and where the log is emitted to. It's something useful in environments where it's not easy to define or edit the logging xml configs like scastie.
2. The sourcecode library doesn't provide an implicit for the combination of the file name and line number so two objects need to be instantiated, which also means the `IOs` thunk uses two pointers.
3. Even though the values inferred by sourcecode are statically known and become strings in the class constant pool, the library uses [wrapper objects](https://github.com/com-lihaoyi/sourcecode/blob/main/sourcecode/src/sourcecode/SourceContext.scala#L4C16-L4C27) that require an allocation. The `Logs` code is optimized to avoid capturing the object so the allocation should be elided by the JIT in most cases but it'd be nice to simplify the code and have stronger guarantees without depending on JIT behavior, which can be surprising at times.
4. The log source file and line number are currently part of the log message and a single logger `kyo.logs` is reused. Ideally, the logger name should contain the source info but we'd need to check if there's a way to do that without having to allocate `Logger` instances on each produced log line.
5. Could we cache the `logger.is*Enabled` flags on class loading? That'd allow us to avoid allocating the `IOs` thunk when the logging is disabled.

**Comment by hearnadam** [comment]
#259 addressed the remaining concerns here, with the exception of 4. There are some mechanisms we could use to cache per-file loggers, but I think the overhead does not fit with Kyo's direction in general.
