### ISSUE TITLE
Contravariant Aborts

### ISSUE THREAD

**Issue by johnhungerford** [getkyo/kyo#156]
`Aborts[E]` is currently invariant with `E`, with the result that each time `Aborts[E].get` or `Aborts[E].fail` is called with a new error type, a new `Aborts` type is added to the intersection:

```scala
def effect(i: Int): Unit > (Aborts[IOError] & Aborts[IllegalArgumentException] & Consoles) =
  for {
    _ <- Consoles.println(s"Chosen number: $i")
    _ <- if i > 50 then Aborts[IOError].fail(new IOError(new Exception(i.toString)))
         else Aborts[IllegalArgumentException].fail(new IllegalArgumentException(i.toString))
  } yield ()
```

This is problematic for a couple reasons. First, as more error types are included, the effect type gets cluttered. Second, there is no easy way to handle multiple aborts at the same time. Handling them separately can be a pain, especially since the compiler seems to have hard time separating multiple abort types out without help from verbose explicit type annotation.

Contrast this with working directly with `Either`. When composing `Either`'s of different types, the compiler will automatically find the most specific supertype of the error channel, and this common error type can be handled for both:

```scala
// scala 3 compiler will infer this as: Left[IOError | IllegalArgumentException, Nothing]
// scala 2 compiler will infer this as: Left[Throwable, Nothing]
def effect(i: Int) =
  if i > 50 then Left(new Exception(i.toString))
  else Left(new IllegalArgumentException(i.toString))
```

If `Aborts[E]` were made contravariant with `E`, you would get this same behavior, since `F[X[A] & F[X[B]] =:= F[X[A | B]]` when `F[A]` is contravariant with `A` and `X[A]` is contravariant with `A`.

---

The alternative would be to come up with combinators to collect multiple `Aborts` effects and unify them to a common supertype, but this is what I have so far not been able to accomplish in any ergonomic way. I suspect that at some point macros would be needed to simplify the effect-handling process.

**Comment by fwbrasil** [comment]
I agree this would be a good improvement. Both `Envs` and `Aborts` used to have this behavior but I had to remove it after  Scala 2 support was added. I don't recall the details of the issues to make it work in Scala 2, though.

**Comment by fwbrasil** [comment]
@johnhungerford I've just picked up this issue but I'm having trouble with the solution to remove the value from the nested type parameter as you suggested on Twitter. If I ask the compiler to infer types, it ends up producing an incorrect pending set: https://scastie.scala-lang.org/mIoqa2m0TuWU3j1ZvMSTGw

This is the initial change in case you want to play with it: https://gist.github.com/fwbrasil/66bfa8deae43c13f3b3537b5e145e786

**Comment by fwbrasil** [comment]
I found a way to make it work with a match type \o/

```scala
    type Elide[V] =
        V match
            case Nothing => Any
            case V       => Aborts[V]
            
     def run[T, S, V2](v: T < (Aborts[V | V2] & S))(
            using
            Tag[Aborts[V]],
            ClassTag[V],
            Flat[T < (Aborts[V] & S)]
        ): Either[V, T] < (S & Elide[V2]) 
```

I think I had tried something similar in the past and it didn't work. It could be working because of the recent improvements in Scala 3.4.
