### ISSUE TITLE
State and Writer effects

### ISSUE THREAD

**Issue by ghostdogpr** [getkyo/kyo#195]
Hi!

I am evaluting Kyo as a potential replacement for `ZPure`. I am using `ZPure` in a project with high traffic (gaming) and complex business logic and the amount of allocations is staggering (cats `IndexedReaderWriterStateT` is worse), so Kyo's low overhead approach is definitely interesting.

While I see clearly how to replace the reader and the error effects, I don't see clear equivalents for state and writer. `Locals` are only modified in their inner scope so I don't think it can be used. I can use `Envs[AtomicRef[A]]` but that is overkill and even slower because we don't need concurrent modifications.

Is there a way to do it that I am not seeing? If not, is that something that could be added?

**Comment by ghostdogpr** [comment]
@fwbrasil in case you're interested, I have a small repo with a benchmark comparing various solutions for a reader/writer/state: https://github.com/ghostdogpr/mtl-benchmarks

Each benchmark op is running 1000x a set of 3 operations: read from an env, write a log and modify a state (which is a simplified version of the business logic I run in production).
Here's the commit adding kyo: https://github.com/ghostdogpr/mtl-benchmarks/commit/34304738b58ac40867e2839cbafbffb05658d7b8 (I used `Vars` for the writer, will replace after you change `Sums` like you mentioned).

Kyo fares pretty well overall but is still way slower (and allocates more) than ZPure.
```
[info] Benchmark                               Mode  Cnt     Score     Error  Units
[info] Benchmarks.MTLReaderWriterStateEither  thrpt    5  1522.572 ± 117.366  ops/s
[info] Benchmarks.MTLReaderWriterStateIO      thrpt    5   552.119 ±  55.575  ops/s
[info] Benchmarks.MTLZIO                      thrpt    5   581.533 ± 575.613  ops/s
[info] Benchmarks.MTLZPure                    thrpt    5  1983.791 ±  85.645  ops/s
[info] Benchmarks.ZPure                       thrpt    5  6142.444 ± 120.744  ops/s
[info] Benchmarks.kyo                         thrpt    5  2058.202 ± 264.282  ops/s
[info] Benchmarks.readerWriterStateIO         thrpt    5   919.416 ±   9.923  ops/s
```
Hope this is interesting. Let me know if I did something wrong or unidiomatic.

**Comment by fwbrasil** [comment]
Nice! Thank you for providing the benchmark. I'll take a look tomorrow. At first glance, I'd be careful to assume that the benchmark reflects real-world usage, since it essentially involves suspensions without regular transformations. The majority of the workload for effect systems actually involves much more regular transformation then suspension, for which Kyo is highly optimized.

**Comment by fwbrasil** [comment]
Sorry, it's taking some time for me to get to your benchmark because I'm dealing with the recent community issues. I have to finalize some other things today but I'm planning to pick this up early next week.

**Comment by fwbrasil** [comment]
I've pushed a few optimizations and a benchmark: https://github.com/getkyo/kyo/commit/0c38d972fead23f69294adf1dd6c18c63ac6ae03. Results:

Baseline
```
[info] Benchmark                             Mode  Cnt        Score     Error   Units
[info] MtlBench.syncKyo                     thrpt    5     3966.099 ± 164.480   ops/s
[info] MtlBench.syncKyo:gc.alloc.rate       thrpt    5     9386.199 ± 389.938  MB/sec
[info] MtlBench.syncKyo:gc.alloc.rate.norm  thrpt    5  2481929.759 ±   0.130    B/op
[info] MtlBench.syncKyo:gc.count            thrpt    5       42.000            counts
[info] MtlBench.syncKyo:gc.time             thrpt    5       24.000                ms
```

Optimized
```
[info] Benchmark                             Mode  Cnt        Score      Error   Units
[info] MtlBench.syncKyo                     thrpt    5     4673.740 ±  585.179   ops/s
[info] MtlBench.syncKyo:gc.alloc.rate       thrpt    5     9526.610 ± 1191.542  MB/sec
[info] MtlBench.syncKyo:gc.alloc.rate.norm  thrpt    5  2137613.348 ±  285.864    B/op
[info] MtlBench.syncKyo:gc.count            thrpt    5       36.000             counts
[info] MtlBench.syncKyo:gc.time             thrpt    5       22.000                 ms
```

The version `0.8.11` with the optimizations should be in maven central soon. Could you run the benchmarks again? Also, if you have some time, it'd be great if you could add your benchmarks to Kyo's repo. I added only a target for Kyo: https://github.com/getkyo/kyo/blob/main/kyo-bench/src/main/scala/kyo/bench/MtlBench.scala

**Comment by ghostdogpr** [comment]
It's a bit better:
```
[info] Benchmark                               Mode  Cnt     Score     Error  Units
[info] Benchmarks.MTLReaderWriterStateEither  thrpt    5  1469.051 ±  49.224  ops/s
[info] Benchmarks.MTLReaderWriterStateIO      thrpt    5   522.914 ±  15.181  ops/s
[info] Benchmarks.MTLZIO                      thrpt    5   654.495 ±  34.126  ops/s
[info] Benchmarks.MTLZPure                    thrpt    5  1947.556 ± 101.279  ops/s
[info] Benchmarks.ZPure                       thrpt    5  6216.002 ± 165.547  ops/s
[info] Benchmarks.kyo                         thrpt    5  2392.536 ±  99.506  ops/s
[info] Benchmarks.readerWriterStateIO         thrpt    5   851.274 ±  24.056  ops/s
```
I'll make a PR to add my benchmarks. I think I'll just add `ZPure` and `ReaderWriterStateT` since cats-mtl is just adding a layer of indirection over these.

**Comment by fwbrasil** [comment]
I've pushed the new `Sums` as part of https://github.com/getkyo/kyo/pull/205 and made a few additional optimizations. Although this benchmark is challenging for Kyo given the unusual ratio between effect suspensions and transformations, the performance seems now close to ZPure:

```
[info] Benchmark                               Mode  Cnt        Score      Error   Units
[info] MtlBench.syncKyo                       thrpt    5    13240.931 ± 3369.221   ops/s
[info] MtlBench.syncKyo:gc.alloc.rate.norm    thrpt    5   744179.676 ±   42.513    B/op
[info] MtlBench.syncRWST                      thrpt    5     5473.030 ±  195.463   ops/s
[info] MtlBench.syncRWST:gc.alloc.rate.norm   thrpt    5  1918913.093 ±  128.072    B/op
[info] MtlBench.syncZPure                     thrpt    5    15106.049 ±  558.116   ops/s
[info] MtlBench.syncZPure:gc.alloc.rate.norm  thrpt    5   553848.465 ±    0.046    B/op
```

I don't have experience with ZPure but it seems this would be the mapping to Kyo effects:

```
type KPure[+W, -S1, +S2, -R, +E, +A] =
    A < (Sums[List[W]] & Envs[S1] & Vars[S2] & Envs[R] & Aborts[E])
```

Could you validate the new APIs and performance? I still have to check a few things before cutting a release but let me know if you'd like a snapshot release. Feel free to submit more PRs with benchmarks if you like, they're very useful to find new optimizations! 🙏

**Comment by fwbrasil** [comment]
> with the most allocated classes being ZPure#Succeed and ZPure#FlatMap

It seems there's a good chance Kyo would be a good performance improvement if that's the case. Its version of `ZPure.succeed` doesn't need a monad allocation and `flatMap` is much more lightweight. For example, it's easy to tip the scales in Kyo's favor by adding a couple more flatMaps:

```scala
    def testKyo: Unit < (Aborts[Throwable] & Envs[Env] & Vars[State] & Sums[List[Event]]) =
        Seqs.traverseUnit(loops)(_ =>
            for
                conf <- Envs[Env].use(_.config)
                event = Event(s"Env = $conf")
                _    <- Sums[List[Event]].add(List(event))
                toAdd = 1
                _    <- Vars[State].update(state => state.copy(value = state.value + toAdd))
            yield ()
        )

    def testZPure: ZPure[Event, State, State, Env, Throwable, Unit] =
        ZPure.foreachDiscard(loops)(_ =>
            for
                conf <- ZPure.serviceWith[Env](_.config)
                event = Event(s"Env = $conf")
                _    <- ZPure.log(event)
                toAdd = 1
                _    <- ZPure.update[State, State](state => state.copy(value = state.value + toAdd))
            yield ()
        )
```

```
[info] Benchmark                               Mode  Cnt       Score      Error   Units
[info] MtlBench.syncKyo                       thrpt    5   12554.050 ± 1375.341   ops/s
[info] MtlBench.syncKyo:gc.alloc.rate         thrpt    5   10153.889 ± 1112.971  MB/sec
[info] MtlBench.syncKyo:gc.alloc.rate.norm    thrpt    5  848208.674 ±    0.108    B/op
[info] MtlBench.syncKyo:gc.count              thrpt    5      39.000             counts
[info] MtlBench.syncKyo:gc.time               thrpt    5      24.000                 ms
[info] MtlBench.syncZPure                     thrpt    5   10173.036 ±  517.448   ops/s
[info] MtlBench.syncZPure:gc.alloc.rate       thrpt    5    7079.987 ±  360.699  MB/sec
[info] MtlBench.syncZPure:gc.alloc.rate.norm  thrpt    5  729864.135 ±  106.791    B/op
[info] MtlBench.syncZPure:gc.count            thrpt    5      32.000             counts
[info] MtlBench.syncZPure:gc.time             thrpt    5      27.000                 ms
```

In my experience, the majority of codebases have significantly more transformations than effect suspensions, which is where Kyo's performance excels.

**Comment by ghostdogpr** [comment]
Thanks a lot for your work on this! Kyo is very exciting!
