### ISSUE TITLE
Scala Native Support

### ISSUE THREAD

**Issue by fwbrasil** [getkyo/kyo#210]
Although I believe Graal Native should be our main focus given the large investment it has and consistently superior performance now with PGO when compared to Hotspot, Scala Native can still offer an interesting and more lightweight alternative to run Kyo in LLVM (maybe even in Wasm?).

This ticket does not require all modules to be compiled to Scala Native. The main target is Kyo's core but it'd be great if other modules can be included as well.

**Comment by fwbrasil** [comment]
Bounty requirements:

1. `kyo-core` and its tests passing in Scala Native
2. Publishing of the new module works correctly

**Comment by kubukoz** [comment]
did a quick dependency check out of curiosity:

- zio doesn't have SN 0.5 support yet (https://github.com/zio/zio/issues/8786), I thought scalatest didn't either but 3.2.18 does
- if you want to start with SN 0.4 you'll need to downgrade izumi-reflect to 2.3.8 + print to 0.8.1

probably best to wait for ZIO

**Comment by fwbrasil** [comment]
@kubukoz thank you for taking a look! 

> zio doesn't have SN 0.5 support yet (https://github.com/zio/zio/issues/8786), I thought scalatest didn't either but 3.2.18 does

For the scope of this ticket, we don't need all modules cross-compiled to Scala Native, only `kyo-core`, but it'd be great if we can cross-compile some other modules as well.

> if you want to start with SN 0.4 you'll need to downgrade izumi-reflect to 2.3.8 + print to 0.8.1

Both should be ok do to. Izumi is only used in tests and benchmarks as a reference implementation now. I don't know what we'd lose downgrading pprint but we'd only need to ensure all tests are passing.

**Comment by DamianReeves** [comment]
As of last week ZIO now has support for Scala Native 0.5.x

**Comment by fwbrasil** [comment]
@hearnadam I'm redistributing Kyo's bounties. Have you been able to work on this? If not, can you cancel the attempt? Thank you!

**Comment by hearnadam** [comment]
Resolved by #866 #873 and #645

**Comment by hearnadam** [comment]
Resolved by #866 #873 and #645
