### ISSUE TITLE
Resolvers: GraphQL via Caliban

### ISSUE THREAD

**Issue by fwbrasil** [getkyo/kyo#216]
GraphQL is a powerful framework for building flexible HTTP clients and servers. Its query representation allows for expressing a wide range of sophisticated access patterns in a straightforward and consistent manner, a notable advantage over traditional REST approaches. For example, a single GraphQL query can retrieve multiple resources, as well as specific fields of those resources, reducing the need for multiple network requests and enabling more efficient data retrieval.

Given the developments in AI, I think the relevance of solutions like GraphQL can increase significantly. It's possible that a large portion of software user interfaces will transition to highly personalized, AI-driven interactions. The flexible and dynamically discoverable nature of GraphQL could make it a great primitive to develop software to be used by AI systems.

[Caliban](https://ghostdogpr.github.io/caliban/) seems a good choice for Kyo's integration for GraphQL. It seems generic and adaptable to different effect systems and its query definition mechanism seems to enable the kind of simple-to-use experience Kyo aims for. Ideally, the new module should integrate with `kyo-tapir`.

**Comment by ghostdogpr** [comment]
Curious about the API would look like. Would it be just that?
```scala
val api: GraphQL[Any] = ??? // call caliban's graphQL function

val a: Unit < Graphqls =
  Graphqls.add(api)

val b: NettyKyoServerBinding < Fibers = // this might require Zios since Caliban is using ZIO internally
  Graphqls.run(a)
```
In addition to that, we can define a `caliban.schema.Schema` for `T < S` so that you can define resolvers using Kyo effects.

Is that what you had in mind?

**Comment by fwbrasil** [comment]
hey @ghostdogpr! Thanks for following up on this. I'd say a "shallow" integration like you're suggesting would be a good initial step but it'd be nice to eventually evolve the module to avoid exposing `ZIO` types and encode APIs as Kyo computations instead. For example, it'd be nice to expose `Interceptor` as based on Kyo instead of ZIO directly. Just wrapping APIs might be enough if the performance overhead doesn't become an issue. We could still use `ZIOs` internally and declare the effect as:

```scala
opaque type Resolvers = ZIOs
```

(btw, what do you think of `Resolvers` instead of `Graphqls`?)

Another angle that would be interesting to explore is allowing arbitrary effects in schemas instead of "pinning" them only to dependency injection and error handling effects. For example, if we introduce an effect similar to `ZQuery`, it'd be great if we could just use it without having to implement a new schema for it.

**Comment by ghostdogpr** [comment]
> hey @ghostdogpr! Thanks for following up on this. I'd say a "shallow" integration like you're suggesting would be a good initial step but it'd be nice to eventually evolve the module to avoid exposing `ZIO` types and encode APIs as Kyo computations instead. For example, it'd be nice to expose `Interceptor` as based on Kyo instead of ZIO directly. Just wrapping APIs might be enough if the performance overhead doesn't become an issue. We could still use `ZIOs` internally and declare the effect as:
> 
> ```scala
> opaque type Resolvers = ZIOs
> ```

Sounds good. Not sure how feasible it is to wrap ZIO in existing tapir integration but it seems like it would be the best ergonomics for Kyo.

> (btw, what do you think of `Resolvers` instead of `Graphqls`?)

`Resolvers` is maybe too generic of a word? The `api` object you would pass to `add(api)` is of type `GraphQL` in Caliban. We also have a type `RootResolver` but I don't think Kyo should use that one since `GraphQL` is more powerful (lets you attach middleware, can be combined, etc).

> Another angle that would be interesting to explore is allowing arbitrary effects in schemas instead of "pinning" them only to dependency injection and error handling effects. For example, if we introduce an effect similar to `ZQuery`, it'd be great if we could just use it without having to implement a new schema for it.

If you have an arbitrary effect in your schema, how does Caliban know how to run it?

**Comment by fwbrasil** [comment]
> Resolvers is maybe too generic of a word? The api object you would pass to add(api) is of type GraphQL in Caliban. We also have a type RootResolver but I don't think Kyo should use that one since GraphQL is more powerful (lets you attach middleware, can be combined, etc).

Good point, but I'd like to iterate on other possible names. `GraphQLs` doesn't match the naming pattern of other Kyo effects.

> If you have an arbitrary effect in your schema, how does Caliban know how to run it?

It seems Caliban already supports ZIO environments? I'm not sure how generic the mechanism is but supporting Kyo's pending effects should be similar to handling ZIO environments but with a contravariant type parameter. The user would then have to handle effects similarly to how they handle environments with ZIO.

**Comment by ghostdogpr** [comment]
The thing is Caliban is built on top of ZIO, so if you use the environment on one side (schema), we are able to propagate it all the way to the other side (http layer) because all internal methods in between also take a ZIO. Similarly, Caliban uses ZQuery internally so it's not possible to use a replacement for optimizations (different fields resolvers can only see each other if they share the same ZQuery `DataSource`).

**Comment by fwbrasil** [comment]
I see. I thought Caliban was more generic internally since it supports other effect systems as well. I wonder if there'd be a way to encode Kyo computations within ZIO to overcome this limitation. Maybe something like:

```scala
trait Runner[+S]:
    def apply[T](v: T < (S & ZIOs)): Task[T]

type KIO[+T, -S] = ZIO[Runner[S], Throwable, T < S]
```

It'd have a performance penalty, though. I think just providing support for `ZIOs`, which includes `Fibers` and `IOs`, should be enough for an initial integration. We should be able to integrate `Envs` as well once `ZIOs` supports it.

**Comment by fwbrasil** [comment]
Bounty requirements:

1. Initial "shallow" integration with Caliban via `ZIOs`.
2. Exploration and follow up ticket creation for a "deep" integration where `ZIO` is hidden from the user in all APIs.

**Comment by ghostdogpr** [comment]
/attempt #216

I'll work on this:
- allow `Schema` derivation when using Kyo (with `ZIOs` and probably `Aborts`)
- expose `Resolvers` as a new effect wrapping caliban's `GraphQL`
- turn this into a running API server using kyo's tapir integration
- (bonus) experiment the `Runner` approach above to support arbitrary effects

**Comment by fwbrasil** [comment]
Great news, thank you @ghostdogpr!!!
