### ISSUE TITLE
Envs.Elide cannot be reduced for uninhabitable intersections

### ISSUE THREAD

**Issue by johnhungerford** [getkyo/kyo#231]
When I try to compile the following:

```scala
val effect: Unit < Envs[String & Int & Boolean] = ???
val provided: Unit < Envs[Int & Boolean] = Envs[String].run("string")(effect)
```

I get the following error:

```
[error]     |                  Found:    Unit < kyo.Envs.Elide[Int & Boolean]
[error]     |                  Required: Unit < kyo.Envs[Int & Boolean]
[error]     |
[error]     |                  Note: a match type could not be fully reduced:
[error]     |
[error]     |                    trying to reduce  kyo.Envs.Elide[Int & Boolean]
[error]     |                    failed since selector Int & Boolean
[error]     |                    is uninhabited (there are no values of that type).
```

It looks like the issue is that match types won't reduce when it recognizes that type intersection being matched is uninhabitable (there cannot be a value of that type). Since this will frequently be the case for `Envs` intersections, I don't think match types will work here.

I see two alternatives:

1. Make `Envs` contravariant with `E` so that types are tracked by union rather than intersection.
2. Use a type class with an inner (dependent) type to derive the "remainder"

**Comment by fwbrasil** [comment]
thanks for the report! I agree with making `Envs` contravariant. I also noticed this other bug with the new encoding: https://github.com/getkyo/kyo/issues/215

**Comment by hearnadam** [comment]
I personally don't see the value of using union types in the `Env`. Happy to try my hand at a PR this week.

**Comment by johnhungerford** [comment]
My preference is for approach 2. In general, I've found match types don't work super well and I wouldn't recommend making decisions around them. I would only use unions in those cases where it makes semantic sense, like aborts.

Deriving the remainder of a dependency intersection is not too complicated (from discord):

```scala
type HasEnv[E, ES]:
  type Out

trait LowPriorityHasEnvs:
  given hasEnv[E, ER]: HasEnv[E, E & ER] with
    type Out = Envs[ER]

object HasEnv extends LowPriorityHasEnvs:
  given isEnv[E]: HasEnv[E, E] with
    type Out = Any
```

**Comment by fwbrasil** [comment]
For visibility: we had a [discussion](https://discord.com/channels/1087005439859904574/1087005440623259681/1222610350688436305) on this topic yesterday reached a conclusion that using different variances for `Envs` and `Aborts` is necessary for soundness, so we'd need something like approach 2. 

Thank you for your wisdom here @johnhungerford! If this change ends up making the match type not necessary anymore, I think we should try to move back to Scala 3.3 since 3.4 isn't an LTS release. `Elide` only worked on 3.4.

**Comment by fwbrasil** [comment]
@hearnadam @johnhungerford would one of you be able to pick this up? I wanted to cut a new release and it'd be nice to have this fixed for it.

**Comment by johnhungerford** [comment]
@fwbrasil I'll take a stab at it

**Comment by fwbrasil** [comment]
fixed by https://github.com/getkyo/kyo/pull/240
