### ISSUE TITLE
Resources close with Effects

### ISSUE THREAD

**Issue by jamesward** [getkyo/kyo#233]
I have an effectful `close` on a `Closeable`:
```scala
case class MyResource(id: String) extends Closeable:
  override def close(): Unit =
    IOs.run(Fibers.run(req(uri"${scenarioUrl(8)}?close=$id")))
```

It'd be great if that could just be:
```scala
case class MyResource(id: String) extends Closeable:
  override def close(): Unit < Fibers =
    req(uri"${scenarioUrl(8)}?close=$id")
```

**Comment by hearnadam** [comment]
A few quick thoughts after reviewing the existing `resources` implementation:

- Java `Closable` can throw - yet we directly wrap it in `IO`. Does this need to be handled?
  - https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html
- It should be simply to create our own trait `Closeables` which we can use for type bounding on the API;
  - `def acquireEffectful[T <: Closeables](resource: => T < IOs): T < Resources =` - needs a better name
  - Then the Java compatible API can be defined in terms of the effectful API
- Supporting multiple effect types in the same queue seems problematic... @fwbrasil any ideas?

**Comment by johnhungerford** [comment]
Instead of requiring users to implement a new type, how about replacing adding a more general `acquireRelease` that supports an `IOs` cleanup:

```scala
def acquireRelease[T, S](resource: => T < S)(release: T => Unit < IOs): T < (S & Resources) =
    resource.flatMap(r => ensure(release(r)).andThen(r))
```

Then we can implement `acquire` as:

```scala
def acquire[T <: Closable, S](closeable: => T & S): T < (S & Resources) =
   acquireRelease(closeable)(c => IOs(closeable.close()))
```

**Comment by hearnadam** [comment]
The reason for needing a new type is to support arbitrary effects via a type parameters. I am inclined to believe that we should not worry about that for now. I will cut a PR this week to implement a basic IOs based `acquireRelease`

**Comment by fwbrasil** [comment]
`Resources` already provides a more low-level API:

```scala
def ensure(v: => Unit < IOs): Unit < Resources
```

The challenge with this change is that `Resources` has to rely on `IOs.ensure` that provides a different flow to ensure execution even in the case of a fiber interruption/cancellation. I can't see a way to support arbitrary effects but maybe we could at least support `Fibers`? We'd need a `Promise` to ensure close finishes before returning. 

```scala
    def run[T, S](v: T < (Resources & S)): T < (Fibers & S) =
        Queues.initUnbounded[Unit < Fibers](Access.Mpsc).map { q =>
            Fibers.initPromise[Unit].map { p =>
                def close: Unit < IOs =
                    q.close.map {
                        case None =>
                            bug("Resources finalizer queue already closed.")
                        case Some(l) =>
                            Fibers.run(Seqs.collectUnit(l)).map(p.become(_).unit)
                    }
                IOs.ensure(close) {
                    local.let(q)(v).map { r =>
                        p.get.andThen(r)
                    }
                }
            }
        }
```
