### ISSUE TITLE
More Randoms

### ISSUE THREAD

**Issue by jamesward** [getkyo/kyo#234]
I'd like some more `Randoms` :)

Like:
```scala
  def nextString(length: Int): String < Fibers =
    val lettersFiber = Fibers.parallel:
      Seq.fill(length):
        Randoms.nextValue('a' to 'z')

    lettersFiber.map { chars =>
      chars.mkString
    }

  def nextBytes(length: Int): Array[Byte] < Fibers =
    val random = java.util.Random()
    val array = Array.ofDim[Byte](length)
    random.nextBytes(array)
    IOs(array)
```

**Comment by hearnadam** [comment]
Perhaps these APIs are more suited toward a more generic Generator API similar to ZIO test generators.

Perhaps pessimistic of me, but I think the Random API should be fast and serve as a building block for other APIs. That being said, there may still be room for more functionality.

**Comment by jamesward** [comment]
Amazing! Thanks for the quick turnaround.
