### ISSUE TITLE
Flaky (slow) FIbers test

### ISSUE THREAD

**Issue by hearnadam** [getkyo/kyo#260]
'multiple fibers' test is reaching 5 second timeout (intermittently). Is this a bug in the test? Or are we facing non-determinism with fibers?

```
[info] - multiple fibers *** FAILED *** (5 seconds, 6 milliseconds)
[info]   kyo.fibers$package$Fibers$Interrupted$:
[info]   ...
```

**Comment by fwbrasil** [comment]
It seems to be the one under `interrupt`? I haven't noticed flakiness in my machine or in CI. Does it fail consistently for you? Do you see any GC warnings? This benchmark can allocate a lot since it has three fibers in a hot loop that need to be preempted.

**Comment by hearnadam** [comment]
It's unfortunately hard to replicate. I saw this happen 2-3 times in the last few weeks when running `test` under `kyo-core` (or potentially `kyo`) project. I don't remember seeing any GC warnings...

**Comment by fwbrasil** [comment]
Do you mind sharing the CPU architecture? I've tried running the test several times in a row but no luck as well. Can you try the same?

```
(0 until 1000).foreach { i =>
    s"multiple fibers $i" in runJVM {
        for
            started      <- Latches.init(3)
            done         <- Latches.init(3)
            fiber1       <- Fibers.init(runLoop(started, done))
            fiber2       <- Fibers.init(runLoop(started, done))
            fiber3       <- Fibers.init(runLoop(started, done))
            _            <- started.await
            interrupted1 <- fiber1.interrupt
            interrupted2 <- fiber2.interrupt
            interrupted3 <- fiber3.interrupt
            _            <- done.await
        yield assert(interrupted1 && interrupted2 && interrupted3)
    }
}
```

**Comment by hearnadam** [comment]
M1 Pro

**Comment by hearnadam** [comment]
Using your foreach snippet with 10K run, I saw 7 failures.

I also intermittently saw the latency spike between 120ms - ~1.5s. Most of the iterations had a time of around 30-50ms
