### ISSUE TITLE
Aborts effect is very slow with its use of Izumi

### ISSUE THREAD

**Issue by lukestephenson** [getkyo/kyo#275]
When running Kyo applications, performance is slower than expected due to the Aborts effect handling. Specifically the type comparisons [here](https://github.com/getkyo/kyo/blob/e748b7ca4645b5de9b1b208f5d2e6bbad7f9bf2e/kyo-core/shared/src/main/scala/kyo/aborts.scala#L51) are generating a huge amount of memory allocations and are the suspected cause of the problem.

Introduced in https://github.com/getkyo/kyo/releases/tag/v0.9.2 as part of resolving #244 in PR #254. Running the above code with version `0.9.1` is substantially faster.

This was initially discovered while experimenting with kyo and writing a Kafka producer. That code is available if it helps with resolving https://github.com/lukestephenson/kyo-playground/blob/main/src/main/scala/playground/KyoKafkaProducer.scala.

Originally raised on discord https://discord.com/channels/1087005439859904574/1087005440623259681/1230729800751251567

**Comment by fwbrasil** [comment]
I was taking a look at how ZIO handles type failures and it doesn't use tags like Kyo does. The reflection happens via user-provided partial functions that will match the correct types without a need for tags:

```scala
  final def catchSome[R1 <: R, E1 >: E, A1 >: A](
    pf: PartialFunction[E, ZIO[R1, E1, A1]]
  )(implicit ev: CanFail[E], trace: Trace): ZIO[R1, E1, A1] 
```
https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ZIO.scala#L358

Optimizing the use of Izumi tags seems difficult, we'd probably need a new tag implementation. Maybe we could adopt ZIO's approach instead? The API would have to change to something like:

```scala
val a: Int < Aborts[Ex1 | Ex2] = ...
val b: Int < Aborts[Ex2] =
    Aborts.runCatching(a) {
        case ex: Ex1 => 42
    }
val c: Int < Aborts[Ex1] =
    Aborts.runCatching(a) {
        case ex: Ex2 => 42
    }
val d: Int < Any =
    Aborts.runCatching(a) {
        case ex: Ex1 => 42
        case ex: Ex2 => 42
    }
val e: Either[Ex1 | Ex2, Int] < Any
    Aborts.runEither(computation)
```

**Comment by hearnadam** [comment]
The new API seems preferable to me.

**Comment by lukestephenson** [comment]
The suggested API looks good to me. Make this change appears to affect a lot of kyo though (which I'm fine with if it is the case - I just wanted to see if this was something that I could help with, but kyo appears fairly coupled to izumi at the moment and this appears to beyond what I could assist with at the moment).

**Comment by fwbrasil** [comment]
No worries! I've been more busy with the scheduler work recently but I can try to pick this up in the next days. There shouldn't be any blockers with the suggested approach but it'll require major changes to the effect.
