### ISSUE TITLE
`Kyo-Scheduler`: `scala-js-macrotask-executor` as `ExecutionContext` on JS platform

### ISSUE THREAD

**Issue by HollandDM** [getkyo/kyo#302]
`kyo-scheduler/js` is using the default `scala.scalajs.concurrent.QueueExecutionContext` of `scalajs`. Although not included in the `scala-js` official repo, [scala-js-macrotask-executor](https://github.com/scala-js/scala-js-macrotask-executor) is usually recommended as the optimal `ExecutionContext` implementation for use in any Scala.js project.

If there is no specific requirements, I think we can safely use `scala-js-macrotask-executor` instead of `scala.scalajs.concurrent.QueueExecutionContext`

**Comment by fwbrasil** [comment]
I tried making this change but faced two issues:

1. For some reason, the latest version of `scala-js-macrotask-executor` `1.1.1` doesn't provide Scala 3 artifacts. I had to use `1.0.0` instead: https://repo1.maven.org/maven2/org/scala-js/scala-js-macrotask-executor_3/
2. The build takes much longer with the change
![image](https://github.com/getkyo/kyo/assets/831175/8997c94a-01df-4901-a122-aeb63337b9f0)

I've pushed a branch with the attempt: https://github.com/getkyo/kyo/compare/scala-js-macrotask-executor?expand=1
