### ISSUE TITLE
Documentation: example for Aborts won't compile

### ISSUE THREAD

**Issue by sanssushi** [getkyo/kyo#316]
This  Aborts example from the README creates a TypeMismatch Error:
```scala
val a: Int < Aborts[String] = 
  Aborts.get(Right(1))
```
```
[error] 9 |    val a: Int < Aborts[String] = Aborts.get(Right(1))
[error]   |                                             ^^^^^^^^
[error]   |                                             Found:    Right[Nothing, Int]
[error]   |                                             Required: kyo.Aborts[Any]
```

However, this works:
```scala
val a: Int < Aborts[String] =
  Aborts[String].get(Right(1))
```

(using Scala 3.4.1, kyo 0.9.2)

**Comment by hearnadam** [comment]
Hey @sanssushi, this is because the README was published prior to the release of the new Aborts encoding. @fwbrasil we should have a staging readme to prevent this issue. When the next release is published, this should be fixed.

**Comment by hearnadam** [comment]
@sanssushi can you try with 0.9.3? https://github.com/getkyo/kyo/releases/tag/v0.9.3

**Comment by sanssushi** [comment]
Hey @hearnadam, the example compiles with v0.9.3!
