### ISSUE TITLE
Private HasAborts prevents abstraction of run methods

### ISSUE THREAD

**Issue by johnhungerford** [getkyo/kyo#325]
Now that `HasAborts` is in a private object (`internal`), it's impossible to define a generic method that calls `Aborts.run`. Here is an example from ZiKyo that now fails:

```scala 3
        def someAbortsToOptions[E1: ClassTag](
            using
            ha: Aborts.HasAborts[E1, E],
            t: Tag[Aborts[E1]],
            f: Flat[A < (S & Aborts[E])]
        ): A < (S & ha.Remainder & Options) =
            Aborts.run[E1](effect).map(e => Options.get(e.toOption))
```

The above code block results in the following compilation error:
```
type HasAborts is not a member of object kyo.Aborts.
```

Can we make `HasAborts` public again? (I notice `HasEnvs` is still public.)

**Comment by johnhungerford** [comment]
Opened PR: #326

**Comment by fwbrasil** [comment]
fixed by https://github.com/getkyo/kyo/pull/326
