### ISSUE TITLE
Speed up build

### ISSUE THREAD

**Issue by fwbrasil** [getkyo/kyo#342]
I've noticed Kyo's codebase is taking longer to compile for some time now. It seems the linting compiler flags added some time ago are the main culprit. Removing these flags produced a significant speedup in an initial test:

```
"-Wvalue-discard",
"-Wunused:all",
"-language:strictEquality"
```

**Comment by fwbrasil** [comment]
I've tried adding the new option `ThisBuild / usePipelining := true` that was [recommended on reddit](https://www.reddit.com/r/scala/comments/1d0ga7k/scala_3_usepipelining_build_flag_is_a_game_changer/) but it seems to infer a wrong compilation order and fails:

```
[error] -- [E008] Not Found Error: /Users/fwbrasil/workspace/kyo/kyo-scheduler/jvm/src/main/scala/kyo/scheduler/package.scala:6:11
[error] 6 |import kyo.stats.internal.StatsRegistry
[error]   |       ^^^^^^^^^
[error]   |       value stats is not a member of kyo
```

Removing the flag makes the build work again.

**Comment by regiskuckaertz** [comment]
Maybe try https://scans.gradle.com/?_gl=1*ut6ed*_ga*MjA0NjI5MzM3NC4xNzE2NzEwNzM4*_ga_7W7NC6YNPT*MTcxNjcxMDczNy4zLjAuMTcxNjcxMDczNy42MC4wLjA.#sbt

**Comment by kyri-petrou** [comment]
I know this doesn't solve the issue, but the build should be considerably faster starting with Scala 3.5.x since they fixed unused imports linting performance. Note that 3.5.0-RC1 is already out already in case you want to test it
