### ISSUE TITLE
Rename this project to Kyos

### ISSUE THREAD

**Issue by hearnadam** [getkyo/kyo#429]
Given the implications of pending effects being plural, @kitlangton and I think it's only fitting that we rename the project.

Otherwise we plan to commit mutiny.

**Comment by carlosedp** [comment]
To give @fwbrasil more work... I'd prefer to have all effects singular... like `IO`, `Fiber`, `Console` and so on... :)

**Comment by fwbrasil** [comment]
For background on the current design: the initial versions of Kyo where focused on providing effects for existing monads like `Future`/`Futures`, `Try`/`Tries`, etc. Using plurals was a good way to avoid having to have effects named as `FutureEffect`, `TryEffect`, etc.

The design changed over time and the parity with monads is not as common. For example, even `Fibers` use a `FiberGets` effect under the hood. Given that, I think we could move away from plurals for effects.

**Comment by fwbrasil** [comment]
fixed by https://github.com/getkyo/kyo/pull/572
