### ISSUE TITLE
`.pure` should accept `T < Any` where `T` contains an intersection type

### ISSUE THREAD

**Issue by hearnadam** [getkyo/kyo#430]
When working with @kitlangton on #203, I noticed that the `Flat` bound on `T` ruins our ability to get the value from Kyos resulting in a `TypeMap[A]` when A was an intersection.

https://github.com/getkyo/kyo/blob/main/kyo-core/shared/src/main/scala/kyo/package.scala#L38-L45

I have an idea of how to solve this, but I need to ensure it is sound.

**Comment by fwbrasil** [comment]
fixed by https://github.com/getkyo/kyo/pull/432
