### ISSUE TITLE
Incorporate zikyo into the main repo

### ISSUE THREAD

**Issue by fwbrasil** [getkyo/kyo#451]
I've been noticing a high interest in zikyo's ZIO-like fluent API. Given how important the API will likely become, it'd be ideal if it's under the `kyo` package and built with the other modules so we don't have issues with syncing versions over time. I spoke to @jiveshungerford in private and he's open to moving zikyo to `getkyo/kyo`.

John raised a couple aspects for us to consider with the move:

1. Is it a separate module? If so, what do we call it? keep it zikyo? kyo-combinators?
2. Can we have it in the same package? So import kyo.* would import the KYO object and all extensions? Or would we have a new subpackage kyo.zikyo or kyo.combinators?

I think it should be a separate module. For the name, `kyo-combinators` seems to work well. Another option is `kyo-syntax` but I think it's confusing. For example, `kyo-direct` is also about syntax.

I'd say keeping the APIs under `kyo` would be ideal. If the user has the module in the classpath, the extensions would be made automatically available.

cc/ @hearnadam

**Comment by johnhungerford** [comment]
@fwbrasil let me know if there's anything we need to add for it to publish properly to Maven. I literally just copied over the zio-core project definition and changed the names. Seems to work ok.

**Comment by fwbrasil** [comment]
fixed by https://github.com/getkyo/kyo/pull/452
