### ISSUE TITLE
Add ZIO style System core effect.

### ISSUE THREAD

**Issue by DamianReeves** [getkyo/kyo#627]
I'm coming from ZIO and was looking to the equivalent of what I would do in ZIO with kyo, and noticed that kyo currently doesn't have a core System effect/service.

I would expect this to provide the same functionality as [ZIO's](https://zio.dev/reference/services/system).

In summary:

- [ ] Access the environment using `env`
- [ ] Access properties via `properties`
- [ ] Access `lineSeparator`

I may also suggest providing support for providing the User's home directory in a platform agnostic manner, but this is admittedly beyond the scope of what ZIO's `System` service provides.

**Comment by sideeffffect** [comment]
> providing the User's home directory in a platform agnostic manner

Maybe something based on https://github.com/dirs-dev/directories-jvm ?
