### ISSUE TITLE
kyo-combinators .when should not abort

### ISSUE THREAD

**Issue by johnhungerford** [getkyo/kyo#725]
Currently the extension method `.when` on a pending value will abort if the predicate is not satisfied. This is not desirable: we should be able to call `.when` on a pending value and have it execute only if the predicate is satisfied but not worry about it short-circuiting the rest of our code block. Instead, it should be like ZIO's `when` and simply return a `Maybe`. If the user wants to abort when the result is empty, it is easy enough to do so.

**Comment by fwbrasil** [comment]
fixed by https://github.com/getkyo/kyo/pull/728
