### ISSUE TITLE
ScalaJS with KyoApp

### ISSUE THREAD

**Issue by dipucian** [getkyo/kyo#784]
I tried starting a scalajs project with `KyoApp`, but code as simple as below doesn't work:
```scala
import kyo.*

object ScalaJsApp extends KyoApp {
  run(for {
    _ <- println("1")
    _ <- println("2")
  } yield {})
}
```
running that in browser shows this error after printing `1`:
```ERROR kyo.logs -- [IOPromise.scala:212:21] uncaught exception java.lang.UnsupportedOperationException: fiber.block is not supported in ScalaJS``` and it never prints `2`
originally I was at `0.12.0`, the same also happens on `0.13.0`

updating to `0.13.1` will see another error at linking time, complaining about ```Referring to non-existent method constructor java.util.concurrent.ThreadFactory.<init>()void```

Is `KyoApp` intended for use in scalajs? Am I missing something? please help

**Comment by dipucian** [comment]
I tried all versions from `0.13.1` down to `0.11.1`, none of them works

**Comment by hearnadam** [comment]
@dipucian the issue with ScalaJS is that there is currently no way to block a Thread, which is how the current KyoApp is supported. 

To fix this issue, there are several changes required:
1. Convert KyoApp `run` method(s) to return a `Fiber[E, A]`
2. Split KyoApp to platform specific `trait`s
    - JVM/Native can continue to use `block`
    - ScalaJS can race a 'keepAlive': `def keepAlive = Clock.sleep(10.minutes).map(_ => keepAlive)` with the 'app' fiber.

Contributions are welcome, or I can take this work up in a few weeks.

**Comment by HollandDM** [comment]
@hearnadam I'd like to give this a try, this that good?

**Comment by hearnadam** [comment]
Sounds good! Let me know if you need help!

**Comment by dipucian** [comment]
Thank you @HollandDM for looking into that.

@hearnadam, I'd like to contribute as well (this issue or other), but I have problem even get it to compile, just `sbt compile` from fresh `git clone` failed, complaining about around the `kyo-bench` project, are there anything special for it to compile?

and for the solution, I tried to skip `KyoApp` and implement it in "userland". I found that just by having `Async.sleep(10.minutes)` in JS project will already fail `fastLinkJS` with
```
[error] Referring to non-existent method constructor java.util.concurrent.ThreadFactory.<init>()void
[error]   called from constructor java.util.concurrent.ThreadFactoryStub$.<init>()void
[error]   called from kyo.scheduler.util.Threads$.apply(java.lang.String)java.util.concurrent.ThreadFactory
[error]   called from constructor kyo.Clock$.<init>()void
[error]   called from kyo.Async$package$Async$.sleep(long,java.lang.String)java.lang.Object
```
I wonder if we have a bigger problem than just `KyoApp`

I looked into the source code, and I'm confused why that linking failed as I don't see any blocking or java specific stuff there.  Please enlighten me if you know the reason.

**Comment by fwbrasil** [comment]
@dipucian thank you for looking into this issue! I imagine the issue with `kyo-bench` could be the JVM version. It requires Java 21 because of the Ox benchmarks. If that's not the case, can you share the errors?

I'm not sure what could be causing the issue with `Async.sleep` in JS. We have tests that use the method in JS for example in `AsyncTest`. Can you share an example reproducing the issue?

**Comment by dipucian** [comment]
@fwbrasil yes, the compile problem is indeed the JVM version, thank you.

And for the linking problem with `Async.sleep`, it only happens on my local branch, sorry for the confusion.
**However** when I switched back to `0.13.2`, similar linking error appears when `IO.Unsafe.run` is later involved:
```[error] Referring to non-existent method constructor java.util.concurrent.ThreadFactory.<init>()void
[error]   called from constructor java.util.concurrent.ThreadFactoryStub$.<init>()void
[error]   called from kyo.scheduler.util.Threads$.apply(java.lang.String)java.util.concurrent.ThreadFactory
[error]   called from constructor kyo.Timer$.<init>()void
[error]   called from private kyo.Async$package$Async$$anon$12.apply$$anonfun$5(kyo.kernel.Safepoint)java.lang.Object
[error]   called from kyo.Async$package$Async$$anon$12.apply(java.lang.Void,scala.collection.immutable.Map,kyo.kernel.Safepoint)java.lang.Object
[error]   called from kyo.Async$package$Async$$anon$12.apply(java.lang.Object,scala.collection.immutable.Map,kyo.kernel.Safepoint)java.lang.Object
[error]   dispatched from kyo.kernel.package$internal$KyoSuspend.apply(java.lang.Object,scala.collection.immutable.Map,kyo.kernel.Safepoint)java.lang.Object
[error]   called from private static kyo.IO$.$anonfun$1$$anonfun$1(kyo.kernel.package$internal$KyoSuspend,scala.collection.immutable.Map,kyo.kernel.Safepoint,java.lang.Void)java.lang.Object
[error]   called from static kyo.IO$.kyo$IO$Unsafe$$$_$_$$anonfun$1(kyo.kernel.package$internal$KyoSuspend,scala.collection.immutable.Map,kyo.kernel.Safepoint)scala.Function1
[error]   called from kyo.IO$Unsafe$.kyo$IO$Unsafe$$$_$handleLoop$1(java.lang.String,java.lang.Object,scala.collection.immutable.Map,kyo.kernel.Safepoint)java.lang.Object
[error]   called from kyo.IO$Unsafe$.runLazy(scala.Function0,null,java.lang.String,null)java.lang.Object
[error]   called from kyo.IO$Unsafe$.run(scala.Function0,null,java.lang.String,null)java.lang.Object
```

And I see that `kyo.scheduler.util.Threads`, which is involved in above stack trace, is also modified in @HollandDM's PR. I'd really appreciate an explanation on why the change is needed. 😄

**Comment by HollandDM** [comment]
The original code was just to satisfy the compiler’s complaint about thread, it was just a dummy class without any concrete method implementation. I think at the time kyo wasn’t aware that scalajs themself had done the same work, so i change the js implementation to use that one.
