### ISSUE TITLE
Support property based testing in Kyo-test

### ISSUE THREAD

**Issue by calvinlfer** [getkyo/kyo#877]
Currently Kyo-test only exposes running tests but does not support property based tests since the underlying library exposes ZIO when using check. This ticket is to improve the DX around property based tests

**Comment by hearnadam** [comment]
The issue is `check` returns a `ZIO`. We should replace `check` with something that returns a Kyo instead (or kyo-test could enable mixing Kyo and ZIO)...

As a temporary bypass, you can just use `ZIOs.get`
```scala
            suite("generators")(
                test("1")(
                    ZIOs.get:
                        check(Gen.int) { n =>
                            assertTrue(n == n)
                        }
                )
            )
```
