### ISSUE TITLE
Reactive streams TCK tests are too slow

### ISSUE THREAD

**Issue by fwbrasil** [getkyo/kyo#938]
A quick test suite is an important design principle of Kyo's codebase. The new tests introduced by https://github.com/getkyo/kyo/pull/896 are taking much longer than all the other tests combined. We need to find a reliable way to execute them faster. cc/ @HollandDM

**Comment by HollandDM** [comment]
Idk why `reactive-streams-tck` run so slow, in `fs2` its also take about 30s for the suites.
we can move `reactive-streams-tck` and `reactive-streams` interrop out of kyo's main repo if we have too.
In the mean time, I'll try to figure things out.

**Comment by HollandDM** [comment]
as far as i can tell, `reactive-streams-tck` use a lot of complicate computations, including the inefficient java concurrent one (i guess?), so it run slow. I created a dummy publisher which use only synchronous expressions and it still takes ~30s to complete
